[workspace]
resolver = "2"

members = [
    "chain-indexer",
    "ergo-node-client",
    "migration"
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
ergo-node-client = { version = "^5.0.12", path = "./ergo-node-client" }
